name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: [bug]
assignees:
  - GrayGalaxy
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I agree to follow the [Code of Conduct](/graygalaxy/react-hooks/blob/main/.github/code_of_conduct.md) that this project adheres to.
          required: true
        - label: I have searched the [issue tracker](/graygalaxy/react-hooks/issues) for a bug report that matches the one I want to file, without success.
          required: true
  - type: dropdown
    attributes:
      label: Relevant Hook(s)
      description: Which hook(s) is not working as intended
      multiple: true
      options:
        - use-event
        - use-local-storage
        - use-on-screen
        - use-online-status
        - use-delayed-render
        - use-media-query
        - use-toggle
  - type: textarea
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: |
        Tell us what you observed...

        - Browser: Chrome / MS Edge / Opera ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant log output (optional)
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
  - type: textarea
    attributes:
      label: Reproduction steps
      description: 'How do you trigger this bug? Please walk us through it step by step.'
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: false
